feat: add capsule search api
codeocean/codeocean-sdk-python pull request #20
Opened 2024-12-31 21:55 UTC by jake-valsamis

- add support for capsule search API, introduced in v3.1
- update Capsule and CapsuleStatus fields according to v3.1 changes:
     - published_capsule --> release_capsule
     - keywords --> tags

2025-01-02 20:14 UTC, zvikagart requested changes

2025-01-02 20:14 UTC, zvikagart commented on src/codeocean/capsule.py
> +class CapsuleOwnership(StrEnum):
This should be named `Ownership` and moved to `components.py`

2025-01-02 20:14 UTC, zvikagart commented on src/codeocean/data_asset.py
> +    next_token: Optional[str] = None
Let's continue to reflect the field ordering from the open api spec

2025-01-03 15:24 UTC, jake-valsamis commented
closing as changes included in  [feat: Code Ocean Version 3.1 updates PR](https://github.com/codeocean/codeocean-sdk-python/pull/21)

2025-01-03 15:24 UTC, closed without merging